### PR TITLE
form validation and conditional messages

### PR DESCRIPTION
**Pull request by james-oldfield**
Set up to the work with the yet-unmerged new API end points. Providing feedback based on where the user has entered incorrect details along with disabling the 'submit' button until this is complete.
#11

### CODE REVIEW

**Comment by nevosegal** [comment]
A few notes:
- I think we should keep the `http://` prefix and not ask the user to specifically type it. We should prepend it to the inputted link.
- Setting the version number as a number value is not good, as version often have `.` which makes this field invalid.
- Not sure we should even put an error message, just a green/red highlight should do. We could use the fields' placeholders to explain when we there are specific requirements of the field.
- Lets add to this pull request a feature that greys out the price input when the user checks the free checkbox.

**Comment by nevosegal** [comment]
Regarding the categories. We could use the `multiple` keyword on a `select` tag. This allows the user to hold down Cmd/Ctrl and choose multiple entries.

**Comment by james-oldfield** [comment]
All valid points you've made - I've already added something to grey out the price upon ticking 'free' - I'll add in the other things now. 

So you don't reckon it's worth having any kind of error messages except under some circumstances e.g. over character limit?

**Comment by james-oldfield** [comment]
Added:
- a little function that adds 'http://' if not already provided
- a conditional red box if there's an error.
- Price required only if free is unticked
- Reverted a lot of input types back to text to prevent invalidating incorrectly.

Things that need doing next in this respect:
- A decision on whereabouts to handle the form fields' idiosyncrasies, e.g splitting down multiple categories etc.
- Need to write a directive for a dropdown box to select predefined categories from the API.

Let me know what you think of most recent commit.

**Comment by james-oldfield** [comment]
Rather negligible at the minute but it might always be nice to add in a 'x characters remaining' when typing in the description box perhaps..

**Comment by PedroQuijadaLeyton** [comment]
:+1: Nice work James.
The toll will have more than one description, but yeah, X characters remaining is a good control measure.

**Comment by nevosegal** [comment]
:+1:

**Pull request merged**
